### PR TITLE
Fixed Regression found in the Column Factor dialogs

### LINKED ISSUE #9651: Error on Opening 'Prepare>Column: Factor >Reorder Levels' Dialog
@rdstern @lilyclements @fran2or @jkmusyoka @derekagorhom
An error occurs in the newly released version (0.8.4.5) when navigating to Prepare > Column: Factor > Reorder Levels....

This happens whether a dataset is loaded or you're simply trying to open the dialog with no data present.
The application throws an error message: "Unhandled exception has occurred in your application."

I've attached this screenshot showing the error prompt.

Image

This issue is worth noting.

### PR DESCRIPTION
**Pull request by Ag-Derek**
Fixes #9651 
I did a couple of test runs and they seem to run fine, the Column factor dialog don't seem to cause the problems found anymore. 
@lilyclements please can you do a stress test and see if everything works fine for you too. 
Thanks

### CODE REVIEW

File: instat/clsRecentFiles.vb [hunk 1]
```diff
@@ -211,27 +211,6 @@ Public Class clsRecentFiles
...
-                If dfTemp.Name = "dlgReferenceLevel" Then
-                    frmMain.SetDefaultValueInReorderLevels()
-                End If
-                If dfTemp.Name = "dlgFactorDataFrame" Then
-                    frmMain.SetDefaultValueInReorderLevels()
-                End If
-                If dfTemp.Name = "dlgCountinFactor" Then
-                    frmMain.SetDefaultValueInReorderLevels()
-                End If
                 dfTemp.ShowDialog()
```
Comment (lilyclements) [inline instat/clsRecentFiles.vb:214]: What did this code do? I want to check that before reviewing. 
I know that we have the functionality to "remember" the variable you accessed the dlg through if you have gone via the right-click menu. Is this impacting that?

Comment (Ag-Derek) [reply instat/clsRecentFiles.vb:214]: This was implemented in such a way that when the user uses the last dialog button it remembers the `setDefaultValueInValueInReorderLevels()`
`setDefaultValueInValueInReorderLevels()` was set such that when the factor dialog was clicked this would automically pick the the first factor in the dataset.

Comment (lilyclements) [reply instat/clsRecentFiles.vb:214]: Ok, so out of interest why is this being removed?

Comment (Ag-Derek) [reply instat/clsRecentFiles.vb:214]: my understanding is that, that particular section gives the error Rodgers found. because there is not dataset in the reogrid, when you select some of the factor dialogs because it cannot pick the factors in the dataset it gives the error.

**Comment by rdstern** [comment]
@derekagorhom I assume you have resolved the regression by getting rid of the new feature of automatically including a factor variable?
If so, then am afraid I have changed my mind, and hence agree with @lilyclements reticence above.  I prefer we live with this problem for now, until you are able to fix it properly, i.e. not try to load a variable when there is no data.

File: instat/frmMain.vb
Comment (ChrisMarsh82) [inline instat/frmMain.vb:1]: Revert changes back and add a check at line 951 to check to see if the dataset exits. If it doesn't the exit out of the procedure

File: instat/clsRecentFiles.vb (hunk 1 above)
Comment (ChrisMarsh82) [reply instat/clsRecentFiles.vb:214]: Revert these changes and just update SetDefaultValueInReorderLevels() to break out if no dataset exists

**Comment by Ag-Derek** [comment]
@ChrisMarsh82 @lilyclements I have added the check
can you review this 
Thanks

**Review by rdstern — DISMISSED** [review]
@Ag-Derek this looks fine to me - and a great relief, and well done.  It is also a great example of a critical issue found and reported by a new member @Rockjunior of the development team.
I really like the example, because who would think of using a factor dialog when there is no data at all.  Answer - well somebody might, and we are trying to produce a package to be used by anyone.  And that sets a much higher standard than just producing a program!

I am approving.  @Emmanuel-Afrifa do you feel able to check the VB code?  If so, and you are happy with it, then please tell @lilyclements so she can merge.  It is fine if not and we'll  ask Vitalis or Patrick or Chris?

File: instat/frmMain.vb
Comment (ChrisMarsh82) [inline instat/frmMain.vb:1]: Simplyfy these changes IsDataSetLoaded should be in SetDefaultValueReorderLevels(). Then the check can be done just once. 

Can you also get IsDataSetLoaded to be in frmMain it would be better if the code within frmMain didn't have to reference frmEditor. Can you check the clsDataBook to see if the dataframe is loaded?

**Review by ChrisMarsh82 — CHANGES_REQUESTED** [review]
Try to write less code. If you need to check a dataset is loaded do it in one place not multiple

File: instat/frmMain.vb
Comment (Ag-Derek) [reply instat/frmMain.vb:1]: Sure i can try that too

**Comment by Emmanuel-Afrifa** [comment]
> I am approving. @Emmanuel-Afrifa do you feel able to check the VB code? If so, and you are happy with it, then please tell @lilyclements so she can merge. It is fine if not and we'll ask Vitalis or Patrick or Chris?

@rdstern I think @ChrisMarsh82 may have already started reviewing the code. Also, as this change touches some other very important and global files like frmMain, I think it will be best for a more experienced developer like @ChrisMarsh82 to review these code changes.

File: instat/frmMain.vb
Comment (Ag-Derek) [reply instat/frmMain.vb:1]: @ChrisMarsh82 Please is it ok if we leave the IsDataSetLoaded function in the frrmEditor, since moving it would require us to have unvell.ReoGrid.Worksheet in the frmmain which requires `Imports unvell.ReoGrid.Events` into Frmmain and setting this up adds more lines of code which we wanted to avoid

**Review by ChrisMarsh82 — APPROVED** [review]
Have not completed functionality test but the code looks fine
