### PR TITLE
Bug fix on pasting multiple columns

### LINKED ISSUE #8815: Edit Menu - Paste New
Hello @rdstern and @N-thony, 

I the edit menu there is an item called Paste New. This takes the data from the clipboard and makes it into its own data frame. Should this menu item be called Paste New Data Frame? I think it would be clearer, Paste new feels a bit ambiguous.

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #8815 
@rdstern @rachelkg @Patowhiz this fixes the pasting of multiple columns. I used the scripts suggested by Patrick in the issue. Have a look.

### CODE REVIEW

File: instat/static/InstatObject/R/data_object_R6.R [hunk 1]
```diff
@@ -670,7 +670,7 @@ DataSheet$set("public", "add_columns_to_data", function(col_name = "", col_data,
       if(require_correct_length) stop("Length of new column must be divisible by the length of the data frame")
       else curr_col <- rep(curr_col, length.out = self$get_data_frame_length())
     }
-    if(use_col_name_as_prefix) curr_col_name = self$get_next_default_column_name(col_name)
+    if(use_col_name_as_prefix) curr_col_name = self$get_next_default_column_name(col_name)[[i]]
```
Comment (Patowhiz) [inline instat/static/InstatObject/R/data_object_R6.R:673]: In what scenario will `self$get_next_default_column_name` function return a list?

**Review by Patowhiz — COMMENTED** [review]
@N-thony also test for any regressions through other dialogs that add new columns

File: instat/static/InstatObject/R/data_object_R6.R (hunk 1 above)
Comment (Patowhiz) [reply instat/static/InstatObject/R/data_object_R6.R:673]: At this point you are already looping through the columns that have been added, why not use the index of the loop to access the specific column name in the column names vector? This will make sure  `self$get_next_default_column_name` returns a single value. It also makes the code consistent, optimal and clear to understand given the loop context.

I think `col_name` and `num_cols` vectors are of the same size.

**Comment by Patowhiz** [comment]
@N-thony, when you make the final code changes and commits, please tag the reviewers to indicate that the pull request is ready for review. Otherwise, I will assume you are still working on it.

@rdstern, please retest the changes made to ensure they fix the bug, then I can proceed with the merge.

**Review by rdstern — APPROVED** [review]
@N-thony that's very nice now.  I am really happy this is working.  @Patowhiz back to you!

**Review by Patowhiz — APPROVED** [review]
